### ISSUE TITLE
stdout maxBuffer length exceeded on very large diffs

### ISSUE THREAD

**Issue by LPLabrys99** [GrantBirki/git-diff-action#13]
This action is failing on pull requests with very large diffs due to what looks like a buffer overflow issue.

The action fails with the following:

```
git diff error: stdout maxBuffer length exceeded
```

For context the PR was approximately 20 lines removed and 20 lines added from about 400 files in the repo. I am calling the action with these inputs:

```yaml
    - uses: GrantBirki/git-diff-action@v2.0.1
      name: Pull request diff
      id: pr-diff
      with:
        json_diff_file_output: pr_diff.json
        raw_diff_file_output: pr_diff.txt
```
